[project]
name = "tfl-visualisation"
version = "0.1.0"
description = "Personal project visualisation time series crowding data for the London underground network"
readme = "README.md"
authors = [
    { name = "lauriejoslin", email = "lauriejosephjoslin@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pandas>=3.0.5",
    "plotly>=6.9.0",
    "pysqlite3>=0.6.0",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]

[project.scripts]
tfl-visualisation = "tfl_visualisation:main"
write_stations = "tfl_visualisation.db:write_stations"
read_stations = "tfl_visualisation.db:read_stations"
delete_stations = "tfl_visualisation.db:delete_stations"
write_crowding = "tfl_visualisation.db:write_naptan_crowding"
delete_crowding = "tfl_visualisation.db:delete_crowding_table"


[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
